### ISSUE TITLE
Synthèse géographique - Classes dynamiques

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_dashboard#10]
Actuellement les bornes des classes de symbologie cartographique est définissable dans les paramètres du module : https://github.com/PnX-SI/gn_module_dashboard/blob/master/config/conf_gn_module.toml.example

On peut ainsi les ajuster pour coller au volume de données dans la synthèse de l'instance GeoNature. 
Par contre quand on applique des filtres taxonomiques, les classes restent les mêmes alors que le volume de données peut être bien plus réduit. 

Du coup, il faudrait que les classes soient dynamiques en fonction du total de données.

**Comment by sig-pnrnm** [comment]
J'étais tombé sur ce plugin dans mes recherches précédentes : 
http://tannerjt.github.io/classybrew-www/examples/basic/
Ca a l'air simple et efficace !

**Comment by lpofredc** [comment]
Sinon, avec une génération des classes en bdd avec la fonction *Window* `ntile` qui permet par exemple de créer des classe de nombres données equitables.

https://docs.postgresql.fr/11/functions-window.html

**Comment by TheoLechemia** [comment]
Fait par Adrien. En créant dynamiquement des classes à intervalles réguliers en partant de la valeur la plus haute
#27
