### ISSUE TITLE
Synthese par entités géographique - Pb affichage des communes

### ISSUE THREAD

**Issue by Amegilla** [PnX-SI/gn_module_dashboard#13]
Bonjour, 

Sur une instance de geonature avec 290 000 données et sur la france entière le chargement de l'affichage par commune échoue.
J'ai modifié les paramètres pour n'afficher que les mailles 10x10km mais le chargement des communes est écrit en dur, peu importe les géométries que l'on mets dans les paramètres.
Après modification du code, la synthese carto en maille 10x10km sur toute la france charge assez rapidement.
J'ai tenté de rajouter les départements dans les paramètres et je rencontre un second problème : le paramétrage des légendes (bornes) est le même peu importe les géométries.
Dans mon cas les bornes définies sont parfaites pour l'affichage par maille mais inadaptée pour des grandes zones comme les départements. Il faudrait pouvoir paramétrer les bornes par géométries...

Par rapport à l'affichage par commune, je pense qu'à grande échelle (nationale dans mon cas) cela n'a pas un énorme intérêt car très peu lisible sur un grand territoire par rapport aux mailles.
Par contre à l'échelle régionale cela redevient intéressant et parlant pour les naturalistes. 
On peut imaginer un onglet (activable ou pas) qui concerne la synthese carto par région. Avec en premier le choix d'une région puis les mêmes options que la synthèse actuelle. Les géométries des communes peuvent être grandement simplifiée pour alléger le calcul, car pour une synthèse le contour précis des communes n'a pas d'importance.

**Comment by camillemonchicourt** [comment]
Oui afficher toutes les communes sur toute la France, c'est surement trop lourd. A voir si une grosse simplification peut combler cela (https://github.com/PnX-SI/gn_module_dashboard/issues/9).

Un paramètre définit les types de zonage proposés : https://github.com/PnX-SI/gn_module_dashboard/blob/master/config/conf_gn_module.toml.example#L4

OK pour le correctif sur celui-ci.

Pour les bornes, les rendre dynamique est une amélioration identifiée : https://github.com/PnX-SI/gn_module_dashboard/issues/10

**Comment by TheoLechemia** [comment]
Fait dans #19
