### ISSUE TITLE
Nom du module Dashboard dans GeoNature

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/gn_module_dashboard#14]
Juste une petite suggestion.

Si je pense que `Dashboard` parle bien aux développeurs, et que c'est plus court dans un code source, je trouve que ça fait tâche dans la liste des modules dispos dans GeoNature : 
![Dashboard](https://user-images.githubusercontent.com/26482054/65495449-138e8700-deb7-11e9-9307-b7b75ac067b4.png)

Je connais pas mal de gens réfractaires aux anglicismes dans les applications, surtout quand un équivalent français existe.
Et je connais aussi d'autres gens, nons spécialement réfractaires aux anglicismes, mais qui ne parlent pas anglais et ne comprendront pas ce qu'il y a derrière :wink:

**Comment by TheoLechemia** [comment]
Tu peux tout à fait renommer la colonne "module_name" dans la table gn_commons.t_modules pour change l'affichage dans le menu latéral. ça n'a aucune incidence sur le code.

**Comment by sig-pnrnm** [comment]
> Tu peux tout à fait renommer la colonne "module_name" [...]

Ok, c'est ce que nous ferons :+1: 
Mais ça pourrait valoir le coup d'harmoniser à la source, non ?

**Comment by camillemonchicourt** [comment]
En effet, la table ``t_modules`` permet de modifier le nom affiché dans l'interface et l’icône de chaque module.
"Tableau de bord" est un peu long pour le menu de gauche, donc on a laissé le nom anglais du module par défaut. 
Libre à chacun de l'ajuster.
