### ISSUE TITLE
Cadre d'acquisition dédoublé

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/gn_module_dashboard#18]
Je viens d'installer le module v0.2.0 sur GN v2.3.2.
Tout fonctionne nickel (bravo à vous !)... enfin presque : je n'explique pas pourquoi j'ai un CA dédoublé avec le même nom dans le graphique des cadres d'acquisitions.
Le pire, c'est que ce n'est pas un vrai doublon... les graphiques sont différents.

J'ai vérifié dans les métadonnées et dans la BDD et il n'est en double nul part.
Seul signe distinctif de ses copains que j'ai identifié : son ID c'est 1 (c'est le CA crée par défaut à l'install d'origine et renommé ensuite chez nous : "Données d'observation de la faune, de la Flore et de la fonge du Parc naturel régional du Pilat").

J'ai creusé un peu mais je sèche... une piste ?
Merci d'avance !

![image](https://user-images.githubusercontent.com/16793813/78810464-afea2800-79c8-11ea-8f54-fadbeaadd84e.png)

**Comment by camillemonchicourt** [comment]
C'est surement la même chose que https://github.com/PnX-SI/gn_module_dashboard/issues/16 ?

**Comment by xavyeah39** [comment]
Oui bien vu je n'avais pas capter l'issue !

**Comment by camillemonchicourt** [comment]
Si tu veux jeter un œil à la vue matérialisée ? Ça vient peut-être de là ?

**Comment by xavyeah39** [comment]
Par contre je ne retrouve pas le comportement hasardeux décrit dans #16.
Chez moi c'est toujours le même affichage et le même CA dédoublé et le fait de rafraîchir ne change rien.
J'ai vérifié les vues matérialisées mais je n'ai rien vu d'anormal non plus...

**Comment by TheoLechemia** [comment]
Duplicate #16
