### ISSUE TITLE
Graphe par entité géographique: chargement systèmatique des communes

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_dashboard#19]
Sur certaines instances national il est préférable de désactiver le graphique par entité géographique pour les communes en modifiant le paramètre `AREA_TYPE` de la manière suivante:
`AREA_TYPE = ["M10", "M5", "M1"]`
Malgrès l'absence des communes dans le paramètre, elle sont chargés par défaut ce qui provoque le plantage de la page

**Comment by Adrien-Pajot** [comment]
Le paramètre à changer est à changer ligne 167 à 169 de dashboard-map.components.ts non ? : 

```
 // Gestion du formulaire contrôlant le type de zonage
 public areaTypeControl = new FormControl("M10");
 public currentTypeCode = "M10"; // par défaut, la carte s'affiche automatiquement en mode "M10"
```
au lieu de 

```
 // Gestion du formulaire contrôlant le type de zonage
 public areaTypeControl = new FormControl("COM");
 public currentTypeCode = "COM"; // par défaut, la carte s'affiche automatiquement en mode "COM"
```

En tout cas cette modif passe chez moi. 

Sinon on retrouve AREA_TYPE à deux autres endroits dans conf_gn_module.toml et conf_schema.toml

C'était ta question ou je suis à côté @TheoLechemia .

**Comment by Adrien-Pajot** [comment]
On retrouve aussi à partir de la ligne 234 de dahsboard_maps_components

`// Initialisation du tableau contenant la géométrie et les données des zonages : par défaut, la carte s'affiche automatiquement en mode "communes"`

**Comment by camillemonchicourt** [comment]
Pour une instance sur toute la France, le chargement des géométries des communes de France est trop lourd et fait planter le module.
L'idée est donc de pouvoir ne définir que des types de maille et dans ce cas ne pas proposer les synthèse géographiques par commune.

**Comment by Adrien-Pajot** [comment]
Oui j'ai bien compris, vu que le titre est chargement systématique des communes ;) 

Mais du coup quand je change le paramètre par défaut L167 en plus de la modification du fichier de config suggérée par Théo, ma liste déroulante ne contient bien que trois entrées. C'est pour ça que je me demande ce qui ne va pas !

**Comment by Adrien-Pajot** [comment]
On pourrait mettre en fichier de config le choix du type de géo par défaut d'ailleurs

**Comment by TheoLechemia** [comment]
Fait
