### ISSUE TITLE
Automatiser le rafraichissement des VM

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_dashboard#24]
"Dans un soucis de performance, des vues matérialisées ont été mises en place. Elles sont renseignées lors de l'installation du module. Il faut rafraichir régulièrement ces vues matérialisées avec la fonction REFRESH MATERIALIZED VIEW pour prendre en compte les nouvelles données intégrées dans la Synthèse.

Une fonction permet de mettre à jour toutes les vues matérialisées du schéma gn_dashboard.

Pour lancer manuellement cette fonction, ouvrez une console SQL et exécutez la requête suivante :

    SELECT gn_dashboard.refresh_materialized_view_data();

Pour automatiser l'éxecution de cette fonction (toutes les heures dans cet exemple), ajoutez la dans le crontab de l'utilisateur postgres :

    sudo su postgres
    crontab -e

Ajouter la ligne suivante en prenant soin de mettre à jour les paramètres de connexion à la base de GeoNature-atlas :

    0 * * * * psql -d geonature2db -c "SELECT gn_dashboard.refresh_materialized_view_data();"

C'est le cas dans export.

**Comment by Adrien-Pajot** [comment]
C'est une commande système qu'il faut mettre dans le install_app du module

**Comment by Adrien-Pajot** [comment]
Peut-être qu'il existe une commande GeoNature pour gérer les crons

**Comment by camillemonchicourt** [comment]
Voir ce qui a été fait dans le module d'Export : 
- Une fonction de création du CRON dans le script d'installation du module (https://github.com/PnX-SI/gn_module_export/blob/master/install_gn_module.py)
- Une fonction ajoutée dans les commandes GeoNature (https://github.com/PnX-SI/gn_module_export/blob/master/backend/commands/geonature_cmd.py#L37)
- Un script SH qui lance cette fonction (https://github.com/PnX-SI/gn_module_export/blob/master/gn_export_cron.sh)

Mais si on intègre ce module dans le cœur de GeoNature, ce sera plutôt à faire de manière globale au niveau de GeoNature et non plus du module.

**Comment by Adrien-Pajot** [comment]
@TheoLechemia a justement dit qu'il était préférable de le faire sur le module dans le cas où l'utilisateur n'installe pas dashboard.

**Comment by camillemonchicourt** [comment]
OK

**Comment by camillemonchicourt** [comment]
La commande de rafraîchissement des VM a été corrigée dans la version 1.2.0 du module, mais la création du CRON n'est plus faite automatiquement à l'installation du module.
