### ISSUE TITLE
Recherche taxonomique avec id_liste 500 figé dans le code?

### ISSUE THREAD

**Issue by hypsug0** [PnX-SI/gn_module_dashboard#35]
Est-ce volontaire de retrouver la recherche de taxon avec un id_liste codé en dur dans le front?

https://github.com/PnX-SI/gn_module_dashboard/blob/c4a71090cc7bd9002685548078448f2712ed264b/frontend/app/dashboard/dashboard-maps/dashboard-maps.component.html#L174-L176

https://github.com/PnX-SI/gn_module_dashboard/blob/c4a71090cc7bd9002685548078448f2712ed264b/frontend/app/dashboard/dashboard-histogram/dashboard-histogram.component.html#L113-L115

Merci

**Comment by camillemonchicourt** [comment]
Non non pas souhaitable en effet.
Au pire un code_liste en dur, mais idéalement un paramètre avec un code_liste en paramètre.

Je pense même que la recherche de taxons devrait se baser sur la liste des espèces présentes dans la synthèse et non pas sur une liste de TaxHub.

**Comment by hypsug0** [comment]
Ok, merci, je regarde pour proposer une PR basée sur la route `api/synthese/taxons_autocomplete?search_name=<recherche>`

**Comment by gildeluermoz** [comment]
Je vois qu'il y a une release en préparation. Il me semblerait utile de merger la PR ci-dessus de @hypsug0 
Non ?

**Comment by TheoLechemia** [comment]
Mergé ! Et bug corrigé : d7cc7b6ad8758479def8d301d65e81dee4b33249

**Comment by gildeluermoz** [comment]
:+1:
