### ISSUE TITLE
Erreur avec la route synthese_per_tax_level/Règne 1.1.0

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_module_dashboard#44]
Suite à une installation en GN 2.9 et dashboard 1.1.0 j'ai constaté cette erreur

j'ai aussi des soucis avec les routes qui contiennent des espace (group INPN 1) mais pas sur toutes mes installation (avec apache c'est ok, moins avec nginx??)

geonature_1_b5fc65247e29 | Exception on /dashboard/synthese_per_tax_level/RÃ¨gne [GET]
geonature_1_b5fc65247e29 | Traceback (most recent call last):
geonature_1_b5fc65247e29 | File "/geonature/geonature/backend/venv/lib/python3.7/site-packages/flask/[app.py](http://app.py/)", line 1949, in full_dispatch_request
geonature_1_b5fc65247e29 | rv = self.dispatch_request()
geonature_1_b5fc65247e29 | File "/geonature/geonature/backend/venv/lib/python3.7/site-packages/flask/[app.py](http://app.py/)", line 1935, in dispatch_request
geonature_1_b5fc65247e29 | return self.view_functions[rule.endpoint](https://app.element.io/**req.view_args)
geonature_1_b5fc65247e29 | File "/geonature/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/[response.py](http://response.py/)", line 19, in _json_resp
geonature_1_b5fc65247e29 | res = fn(*args, **kwargs)
geonature_1_b5fc65247e29 | File "/geonature/geonature/external_modules/dashboard/backend/[blueprint.py](http://blueprint.py/)", line 182, in get_synthese_per_tax_level_stat
geonature_1_b5fc65247e29 | return q.all()
geonature_1_b5fc65247e29 | UnboundLocalError: local variable 'q' referenced before assignment

**Comment by TheoLechemia** [comment]
C'est reglé par un commit ?
