### ISSUE TITLE
No such command 'gn_dashboard_refresh_vm'

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_dashboard#46]
version geonature : 2.9.0
version gn_dashboard : 1.1.0

Bonjour,
Je ne me suis jamais trop penché sur la configuration, ni le fonctionnement de ce module mais j'avais constaté depuis son installation que les informations qu'il me fournissait n'évoluait pas. 
En m'y intéressant aujourd'hui, je constate que la commande `gn_dashboard_refresh_vm`, utilisé par la crontab, n'existe pas au sein de mon venv. L'appelle de `geonature --help` ne renvoie pas une telle commande.
Pensez-vous que cela peut-être lié à une mauvaise installation du module ? 
Comment puis-je rectifier cela ?

**Comment by TheoLechemia** [comment]
La commande n'est pas `geonature dashboard gn_dashboard_refresh_vm` ?

**Comment by cen-cgeier** [comment]
Je n'ai jamais vu d'argument `dashboard` après la commande `geonature`.
La commande que tu proposes ne fonctionne pas non plus :(
Voici une capture des commandes qui me sont disponible :
![image](https://user-images.githubusercontent.com/96542451/195365972-587c6172-19c1-4c74-ab7d-76acb756614b.png)
Et de la configuration de ma crontab :
![image](https://user-images.githubusercontent.com/96542451/195366023-c945c002-a234-4870-b506-ecd82f97ac4f.png)

**Comment by TheoLechemia** [comment]
Effectivement, la commande n'est pas associé au module. Je crois qu'il y a eu une évolution dans le coeur sur l'intégration des commandes des modules. 
J'ai une vieille version du module et j'utilise directement la fonction SQL pour le raffraichissement : 
`0 * * * * psql -d geonature2db -c "SELECT gn_dashboard.refresh_materialized_view_data();"`
(c'est sur le crontab de mon utilisateur postgres, mais plutôt à mettre dans `/etc/cron.d` )

**Comment by camillemonchicourt** [comment]
La commande est ici : https://github.com/PnX-SI/gn_module_dashboard/blob/master/backend/commands/geonature_cmd.py
Mais il faut qu'on revoit la documentation sur la manière de l'appeler.

**Comment by cen-cgeier** [comment]
Merci @TheoLechemia, en effet je vais créer une autre tache cron dans mon  `/etc/cron.d` en attendant de savoir comment résoudre l'appel de la commande `geonature gn_dashboard_refresh_vm`.

Merci @camillemonchicourt. Je ne suis pas sûr qu'il y est uniquement la documentation à revoir. La tâche cron défini par `./install_gn_module.py` ne permet pas de faire fonctionner la commande de `./backend/commands/geonature_cmd.py`

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 1.2.0 du module, compatible avec GeoNature 2.10.0 et plus.
