### ISSUE TITLE
Paramètre pour masquer un graphique

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_dashboard#5]
Ajouter un paramètre par graphique permettant de les afficher ou les masquer.

**Comment by Adrien-Pajot** [comment]
C'est fait non ? Ou la fonctionnalité est de pouvoir vraiment les masquer ?

**Comment by camillemonchicourt** [comment]
Oui vraiment les masquer, virer un des graphiques

**Comment by Adrien-Pajot** [comment]
Traité dans la PR #22
