### ISSUE TITLE
[Dashboard] Erreur 500 sur le module Dashboard

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/gn_module_dashboard#65]
Version GN 2.12.3, Dashboard 1.4.0

Bonjour à tous,
J'ai essayé d'installer le module Dashboard. Je n'ai eu aucun message d'erreur lors de l'installation, mais fausse joie. J'ai plein d'erreur 500 Internal server error lorsque je vais sur le module. Tous les autres modules fonctionnent bien.

![image](https://github.com/PnX-SI/GeoNature/assets/15034095/4cf758b0-ab8b-4a15-a4cc-7be72f886907)

Dans la base geonature2db, je n'ai pas de schéma gn_dashboard, mais j'ai bien le dossier home/geonature/gn_module_dashboard

Je n'ai pas l'impression d'avoir loupé une étape dans l'installation mais le module n'a clairement pas bien été installé. Vous pouvez m'aidez à rattraper le truc ? J'ai fait l'installation 2 fois et même constat.

Merci d'avance pour votre aide !
Vottana

**Comment by camillemonchicourt** [comment]
Oui oui sinon tu peux faire une mise à jour classique de GeoNature.
Mais une installation c'est plus simple.
