### ISSUE TITLE
Release 1.4 n'apparait pas dans la liste des releases

### ISSUE THREAD

**Issue by edelclaux** [PnX-SI/gn_module_dashboard#67]
Périmètre: config de la release 1.4 sur github

La Release 1.4 n'apparait pas dans la liste des releases. 

Il s'agit peut-être d'un comportement volontaire, ou d'une issue connue. Au quel cas désolé pour le spam ! 

![image](https://github.com/PnX-SI/gn_module_dashboard/assets/150020787/d39e9497-6ab5-436f-b2b0-c42a7680785d)

Elle est pourtant bien référencée comme étant la dernière release, et la release de référence.

![image](https://github.com/PnX-SI/gn_module_dashboard/assets/150020787/1239def9-29a8-4829-82f8-6c080714eca9)

**Comment by camillemonchicourt** [comment]
Ouais j'ai jamais compris pourquoi. Je pensais que c'était un problème temporaire de cache mais à priori non... 🤔

**Comment by VincentCauchois** [comment]
J'ai edité la release 1.4.0, sans rien y changer, en cliquant sur le bouton "Update release" visible dans la capture d'écran ci-dessous : 
![image](https://github.com/PnX-SI/gn_module_dashboard/assets/92695617/9dab6621-6273-4776-9800-beddda1da81b)

▶️ ça a résolu le problème.

**Comment by camillemonchicourt** [comment]
OK bien, Github a du planter au moment où on a fait la release.
Merci.

**Comment by edelclaux** [comment]
Top, merci !
